version: "3.9"
services:
   datadog-agent:
    image: "datadog/agent:latest"
    environment:
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_API_KEY: "926db96043058ea3f5f85951ded7b0ea"