logging:
  level:
    co:
      featbit: INFO

featbit:
  spring:
    streaming-url: ${FEATBIT_SAMPLE_STREAMING_URL}
    event-url: ${FEATBIT_SAMPLE_EVENT_URL}
    env-secret: ${FEATBIT_SAMPLE_ENV_SECRET}

server:
  port: ${FEATBIT_SAMPLE_SERVER_PORT:8080}