logging:
  level:
    co:
      featbit: INFO

featbit:
  spring:
    streaming-url: ${FEATBIT_SAMPLE_STREAMING_URL:ws://localhost:5100}
    event-url: ${FEATBIT_SAMPLE_EVENT_URL:http://localhost:5100}
    env-secret: ${FEATBIT_SAMPLE_ENV_SECRET}

server:
  port: ${FEATBIT_SAMPLE_SERVER_PORT:10000}