name: Publish Docker Image For Vue

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Dockerhub image version'
        required: true
  
env:
  TEST_TAG: test
  LATEST_TAG: latest
  VERSION_TAG: ${{ github.event.inputs.version || github.ref_name }}
  APP: demo-dino-game-vue

jobs:
  build-publish:
    name: build and publish image to docker hub
    runs-on: ubuntu-latest
    environment : Production
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:samples/dino-game/interactive-demo-vue"
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP }}:${{ env.VERSION_TAG }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP }}:${{ env.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
            
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP }}
